### ISSUE TITLE
Issues with "Installing NPM Packages" step in okode/ionic@2.0.59

### ISSUE THREAD

**Issue by tamarabartlett** [okode/orbs#4]
I'm trying to use the okode/ionic@2.0.59 orb and I'm struggling to get all the necessary parameters set up. 

I declare the orb in my config.yml like so:
```
version: 2.1
orbs:
  firebase-deploy: azdevs/firebase-deploy@1.0.0
  browser-tools: circleci/browser-tools@1.4.3
  ionic: okode/ionic@2.0.59
```
Then I try to set use the orb to build our ionic project in the workflow
```
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - ionic/ios:
          node-version: "20"
          team-id: "binst-test"
          package-name: "kilnaid-test"
          distribution-provisioning-name: "test"
          development-provisioning-name: "test"
```

I'm seeing the following error:
![Screenshot 2023-08-24 at 2 05 56 PM](https://github.com/okode/orbs/assets/2199918/e610c1f8-7b86-460f-87b0-0ed8f2526e9d)

Am I missing something?
